#+TITLE: Resultados AI no Cimento
#+AUTHOR:    Thiago Lira
#+EMAIL:     thlira15@gmail.com
#+latex_compiler: pdflatex
#+date: \today
#+LATEX_CLASS: beamer
#+LATEX_HEADER: \usepackage[style=authoryear]{biblatex}
#+LaTeX_CLASS_OPTIONS: [bigger]
#+OPTIONS: H:2 toc:t num:t
#+BEAMER_THEME: Madrid 
#+LATEX_HEADER: \bibliography{bibliografia.bib}
#+LATEX_HEADER: \usepackage{animate} 
* Resumo
** Os dados
 :PROPERTIES:
 :BEAMER_opt: allowframebreaks,label=
 :END:
#+BEGIN_EXPORT latex
\begin{table}[]
  \resizebox{\textwidth}{!}{\begin{tabular}{|l|llllll}
\cline{1-1}
\multicolumn{1}{|c|}{\textbf{Unidade/ Variáveis}}         &                                &                              &                           &                             &                               &                               \\ \hline
Composição Química (\%)                                   & \multicolumn{1}{l|}{$AL_20_3$} & \multicolumn{1}{l|}{$SIO_2$} & \multicolumn{1}{l|}{MGO}  & \multicolumn{1}{l|}{RICARB} & \multicolumn{1}{l|}{$P_2O_5$} & \multicolumn{1}{l|}{$F_2O_3$} \\ \hline
Água (\%)                                                 & \multicolumn{1}{l|}{AGP}       &                              &                           &                             &                               &                               \\ \cline{1-3}
Tempo até o começo e fim do endurecimento do material (s) & \multicolumn{1}{l|}{IP}        & \multicolumn{1}{l|}{FP}      &                           &                             &                               &                               \\ \cline{1-3}
Finura Blaine ($cm^{2}$/g)                                & \multicolumn{1}{l|}{SBL}       &                              &                           &                             &                               &                               \\ \cline{1-4}
Resistência Compressiva do Cimento (kPA)                  & \multicolumn{1}{l|}{RC3}       & \multicolumn{1}{l|}{RC7}     & \multicolumn{1}{l|}{RC28} &                             &                               &                               \\ \cline{1-4}
\end{tabular}}
\caption{Variáveis presentes nos dados de expedição de cimento.}
\label{tb:vars}
\end{table}
#+END_EXPORT 
** Treino e Validação 
[[file:figuras/train_dev.pdf]]
** Os dados (Transformações) 
   - Normalizacao Minmax: Valores transformados no intervalo $[0,1]$. 
#+BEGIN_EXPORT latex
          \[
z^*_{i} = \frac{x_i - min(X)}{max(X) - min(X)}
          \]
#+END_EXPORT 
** Os dados (Transformações) 2
   - Reamostragem para frequência diária
     [[file:figuras/slides_dados_antes_resample.pdf]]
** Aplicações de AI existentes 
    - Em [[cite:grecialin]] temos um tratamento temporal dos dados, com regressão lineares treinadas em janelas móveis
    - [[cite:cementlin,nncement]] apresentam uma solucao compatível com o ambiente laboratorial  
** Modelo Linear com Filtragem Exp.
#+BEGIN_EXPORT latex
\animategraphics[loop,controls,width=\linewidth]{50}{figuras/gifs/line-}{0}{9}
#+END_EXPORT 
** Os Modelos de Deep Learning Bayesianos
- Consideram a incerteza do modelo e a propagam até a predição.
- Empíricamente calculam a distribuição de cada predição.
- Escalam facilmente para dezenas ou centenas de milhares de entradas de dados.
- Consomem janelas de W dias do passado (parâmetro customizável) e realizam um número arbitrário de predições.
- Podem facilmente agregar séries exógenas na predição. 
** Treinamento 
#+BEGIN_EXPORT latex
\animategraphics[loop,controls,width=\linewidth]{50}{figuras/gifs/dl-}{0}{9}
#+END_EXPORT 
* Resultados
** Métricas 
   - $R^2$
   Reporta a proporcão da variância da variável dependente que foi explicada pelo modelo.
#+BEGIN_EXPORT latex
\begin{align}
&R^2 = 1 - \frac{SS_{res}}{SS_{tot}} &\\
&SS_{tot} = \sum^n_{i=1} (y_i- \bar{y_i})^2 &\\
&SS_{res} = \sum^n_{i=1} (y_i - \tot{y})^2 &\\
&\bar{y} = \frac{1}{n} \sum^n_{i=1} y &
\end{align}
#+END_EXPORT 
   
** Métricas (2)
- RMSE
Raiz do erro quadrático médio para obtermos um erro na mesma ordem de grandeza da variável alvo.

#+BEGIN_EXPORT latex
\[
RMSE = \sqrt{\sum^n_{i=1}\frac{(\hat{y_i} - y_i)^2}{n}}
\]
#+END_EXPORT 

** Resultados Deep AR 
[[file:figuras/forecast_deep_ar.pdf]]
** Resultados Encoder Decoder Forecaster 
[[file:figuras/forecast_enc_dec.pdf]]
** Resultados Deep Factors
[[file:figuras/forecast_deep_factors.pdf]]
** Bibliografia
 :PROPERTIES:
 :BEAMER_opt: allowframebreaks,label=
 :END:

#+BEGIN_EXPORT latex
\printbibliography
#+END_EXPORT 
