#+TITLE: Resultados AI no Cimento
#+AUTHOR:    Thiago Lira
#+EMAIL:     thlira15@gmail.com
#+latex_compiler: pdflatex
#+LATEX_CMD: pdflatex
#+date: \today
#+LATEX_CLASS: beamer
#+LATEX_HEADER: \usepackage[backend=bibtex]{biblatex}
#+LATEX_HEADER: \bibliography{bibliografia.bib}
#+LaTeX_CLASS_OPTIONS: [bigger]
#+OPTIONS: H:2 toc:t num:t
#+BEAMER_THEME: Madrid 
#+LATEX_HEADER: \usepackage{animate} 
* Resumo
** Os dados
 :PROPERTIES:
 :BEAMER_opt: allowframebreaks,label=
 :END:
#+BEGIN_EXPORT latex
\begin{table}[]
  \resizebox{\textwidth}{!}{\begin{tabular}{|l|llllll}
\cline{1-1}
\multicolumn{1}{|c|}{\textbf{Unidade/ Variáveis}}         &                                &                              &                           &                             &                               &                               \\ \hline
Composição Química (\%)                                   & \multicolumn{1}{l|}{$AL_20_3$} & \multicolumn{1}{l|}{$SIO_2$} & \multicolumn{1}{l|}{MGO}  & \multicolumn{1}{l|}{RICARB} & \multicolumn{1}{l|}{$P_2O_5$} & \multicolumn{1}{l|}{$F_2O_3$} \\ \hline
Água (\%)                                                 & \multicolumn{1}{l|}{AGP}       &                              &                           &                             &                               &                               \\ \cline{1-3}
Tempo até o começo e fim do endurecimento do material (s) & \multicolumn{1}{l|}{IP}        & \multicolumn{1}{l|}{FP}      &                           &                             &                               &                               \\ \cline{1-3}
Finura Blaine ($cm^{2}$/g)                                & \multicolumn{1}{l|}{SBL}       &                              &                           &                             &                               &                               \\ \cline{1-4}
Resistência Compressiva do Cimento (kPA)                  & \multicolumn{1}{l|}{RC3}       & \multicolumn{1}{l|}{RC7}     & \multicolumn{1}{l|}{RC28} &                             &                               &                               \\ \cline{1-4}
\end{tabular}}
\caption{Variáveis presentes nos dados de expedição de cimento.}
\label{tb:vars}
\end{table}
#+END_EXPORT 
** Os dados (2)
- Objetivo (RC28) possui baixa correlação com as variáveis fornecidas.

#+BEGIN_EXPORT latex
\begin{table}[H]
  \centering
\begin{tabular}{lr}
  {} &      RC28 \\
  AGP   &  0.592847 \\
  AL2O3 &  0.463414 \\
  SIO2  & -0.053178 \\
  MGO   & -0.371414 \\
  IP    & -0.132297 \\
  FP    & -0.419800 \\
  SBL   &  0.396555 \\
  PF    & -0.480720 \\
  P2O5  &  0.292252 \\
  \label{tabelacorr}
\end{tabular}
\end{table}

#+END_EXPORT
** Os dados (3)
   
#+BEGIN_EXPORT latex
\begin{figure}[H]
\centering
\includegraphics[width=.3\textwidth]{Figuras/rc28scat.pdf} \hfill
\includegraphics[width=.3\textwidth]{Figuras/rc3scat.pdf} \hfill
\includegraphics[width=.3\textwidth]{Figuras/rc7scat.pdf} 
\caption{Plots de correlação entre os índices e seus valores atrasados.} 
\end{figure}
#+END_EXPORT


** Treino e Validação 
- Série **não estacionária**.
[[file:Figuras/train_dev.pdf]]
** Os dados (Transformações) 
   - Normalizacao Minmax: Valores transformados no intervalo $[0,1]$. 
#+BEGIN_EXPORT latex
          \[
z^*_{i} = \frac{x_i - min(X)}{max(X) - min(X)}
\]
#+END_EXPORT 
** Os dados (Transformações) 2
   - Reamostragem para frequência diária
     [[file:figuras/slides_dados_antes_resample.pdf]]
** Aplicações de AI existentes 
    - Em cite:grecialin temos um tratamento temporal dos dados, com regressão lineares treinadas em janelas móveis
    - cite:cementlin,nncement apresentam uma solucao compatível com o ambiente laboratorial
    - \cite{grecialin}
** Modelo Linear com Filtragem Exp.
#+BEGIN_EXPORT latex
\animategraphics[loop,controls,width=\linewidth]{50}{figuras/gifs/line-}{0}{9}
#+END_EXPORT 
** Os Modelos de Deep Learning Bayesianos
- Consideram a incerteza do modelo e a propagam até a predição.
- Geram uma distribuição de probabilidade para cada predição.
- Escalam facilmente para dezenas ou centenas de milhares de entradas de dados.
- Podem facilmente agregar séries exógenas na predição.
- Não dependem de estacionariedade dos dados. 
    **i.e. podem gerar predições em regimes de anomalia**
** Treinamento 
#+BEGIN_EXPORT latex
\animategraphics[loop,controls,width=\linewidth]{50}{figuras/gifs/dl-}{0}{9}
#+END_EXPORT 
* Resultados
** Métricas 
- $R^2$ 
Reporta a proporcão da variância da variável dependente que foi explicada pelo modelo.
#+BEGIN_EXPORT latex
\begin{align}
&R^2 = 1 - \frac{SS_{res}}{SS_{tot}} &\\
&SS_{tot} = \sum^n_{i=1} (y_i- \bar{y_i})^2 &\\
&SS_{res} = \sum^n_{i=1} (y_i - \hat{y})^2 &\\
&\bar{y} = \frac{1}{n} \sum^n_{i=1} y &
\end{align}
#+END_EXPORT 
   
** Métricas (2)
- RMSE
Raiz do erro quadrático médio para obtermos um erro na mesma ordem de grandeza da variável alvo.

#+BEGIN_EXPORT latex
\[
RMSE = \sqrt{\sum^n_{i=1}\frac{(\hat{y_i} - y_i)^2}{n}}
\]
#+END_EXPORT 

** Resultados (Tabela)
#+BEGIN_EXPORT latex
\begin{center}
\begin{table}[htbp]
\caption{RMSE values by forecast span}
\centering
\begin{tabular}{rr}
\hline
Deep Factors & RMSE\\
\hline
24h & 0.18\\
3d & 2.36\\
7d & 1.83\\
\hline
Deep AR & RMSE\\
\hline
24h & 0.07\\
3d & 1.37\\
7d & 1.44\\
\hline
Encoder Decoder & RMSE\\
\hline
24h & 0.06\\
3d & 0.44\\
7d & 0.80\\
\end{tabular}

\label{tb:rmse}
\end{table}
\end{center}
#+END_EXPORT 

** Resultados (Distribuição)
#+BEGIN_EXPORT latex

\begin{figure}[H]
\centering
\includegraphics[width=.3\textwidth]{figuras/qq_deep_ar.pdf} \hfill
\includegraphics[width=.3\textwidth]{figuras/qq_deep_factors.pdf} \hfill
\includegraphics[width=.3\textwidth]{figuras/qq_enc_dec.pdf} 
\caption{Valores reais plotados contra os valores previstos para análise da distribuição aprendida por cada modelo} 
\label{fig:distr}
\end{figure}

#+END_EXPORT 
** Resultados Deep AR 
[[file:figuras/forecast_deep_ar.pdf]]
** Resultados Encoder Decoder Forecaster 
[[file:figuras/forecast_enc_dec.pdf]]
** Resultados Deep Factors
[[file:figuras/forecast_deep_factors.pdf]]
** Bibliografia
 :PROPERTIES:
 :BEAMER_opt: allowframebreaks,label=
 :END:

#+BEGIN_EXPORT latex
\printbibliography
#+END_EXPORT 
