#+TITLE: Resultados AI no Cimento
#+AUTHOR:    Thiago Lira
#+EMAIL:     thlira15@gmail.com
#+latex_compiler: pdflatex
#+LATEX_CMD: pdflatex
#+date: \today
#+LATEX_CLASS: beamer
#+LATEX_HEADER: \usepackage[backend=bibtex]{biblatex}
#+LATEX_HEADER: \bibliography{bibliografia.bib}
#+LaTeX_CLASS_OPTIONS: [bigger]
#+OPTIONS: H:2 toc:t num:t
#+BEAMER_THEME: Madrid 
#+LATEX_HEADER: \usepackage{animate} 
#+LATEX_HEADER: \usepackage{graphicx} 
* Resumo
** Os dados
 :PROPERTIES:
 :BEAMER_opt: allowframebreaks,label=
 :END:
#+BEGIN_EXPORT latex
\begin{table}[]
  \resizebox{\textwidth}{!}{\begin{tabular}{|l|llllll}
\cline{1-1}
\multicolumn{1}{|c|}{\textbf{Unidade/ Variáveis}}         &                                &                              &                           &                             &                               &                               \\ \hline
Composição Química (\%)                                   & \multicolumn{1}{l|}{$AL_20_3$} & \multicolumn{1}{l|}{$SIO_2$} & \multicolumn{1}{l|}{MGO}  & \multicolumn{1}{l|}{RICARB} & \multicolumn{1}{l|}{$P_2O_5$} & \multicolumn{1}{l|}{$F_2O_3$} \\ \hline
Água (\%)                                                 & \multicolumn{1}{l|}{AGP}       &                              &                           &                             &                               &                               \\ \cline{1-3}
Tempo até o começo e fim do endurecimento do material (s) & \multicolumn{1}{l|}{IP}        & \multicolumn{1}{l|}{FP}      &                           &                             &                               &                               \\ \cline{1-3}
Finura Blaine ($cm^{2}$/g)                                & \multicolumn{1}{l|}{SBL}       &                              &                           &                             &                               &                               \\ \cline{1-4}
Resistência Compressiva do Cimento (kPA)                  & \multicolumn{1}{l|}{RC3}       & \multicolumn{1}{l|}{RC7}     & \multicolumn{1}{l|}{RC28} &                             &                               &                               \\ \cline{1-4}
\end{tabular}}
\caption{Variáveis presentes nos dados de expedição de cimento.}
\label{tb:vars}
\end{table}
#+END_EXPORT 
** Os dados (2)
- Objetivo (RC28) possui baixa correlação com as variáveis fornecidas.

#+BEGIN_EXPORT latex
\begin{table}[H]
  \centering
\begin{tabular}{lr}
  {} &      RC28 \\
  AGP   &  0.592847 \\
  AL2O3 &  0.463414 \\
  SIO2  & -0.053178 \\
  MGO   & -0.371414 \\
  IP    & -0.132297 \\
  FP    & -0.419800 \\
  SBL   &  0.396555 \\
  PF    & -0.480720 \\
  P2O5  &  0.292252 \\
  \label{tabelacorr}
\end{tabular}
\end{table}

#+END_EXPORT
** Os dados (3)
- Objetivo (RC28) possui correlação com os outros índices de RC 
#+BEGIN_EXPORT latex
\begin{figure}[H]
  \centering
  \includegraphics[width=\columnwidth,height=0.7\textheight,keepaspectratio]{figuras/corr_grid.pdf}
\end{figure}
#+END_EXPORT
** Os dados (4)
   
#+BEGIN_EXPORT latex
\begin{figure}[H]
\centering
\includegraphics[width=.3\textwidth]{figuras/rc28scat.pdf} \hfill
\includegraphics[width=.3\textwidth]{figuras/rc3scat.pdf} \hfill
\includegraphics[width=.3\textwidth]{figuras/rc7scat.pdf} 
\caption{Plots de correlação entre os índices e seus valores atrasados.} 
\end{figure}
#+END_EXPORT

** Treino e Validação 
- Série **não estacionária**.
[[file:figuras/train_dev.pdf]]
** Os dados (Transformações) 
   - Normalização Minmax: Valores transformados no intervalo $[0,1]$. 
#+BEGIN_EXPORT latex
          \[
z^*_{i} = \frac{x_i - min(X)}{max(X) - min(X)}
\]
#+END_EXPORT 
** Os dados (Transformações) 2
   - Reamostragem para frequência diária
     [[file:figuras/slides_dados_antes_resample.pdf]]
** Aplicações de AI existentes 
    - Em cite:grecialin temos um tratamento temporal dos dados, com regressões lineares treinadas em janelas móveis
    - cite:cementlin,nncement apresentam uma solução compatível com o ambiente laboratorial
** Modelo Linear com Filtragem Exp.
#+BEGIN_EXPORT latex
\animategraphics[loop,controls,width=\linewidth]{50}{figuras/gifs/line-}{0}{9}
#+END_EXPORT 

** Modelo Econométrico (Processo AR)
   - Processo AR 
   - Usa atrasos de RC3, RC7 e RC28 de respectivamente 3, 7 e 28 dias.
#+BEGIN_EXPORT latex
          \[
          RC28_t = \beta_0 + \beta_1*RC28_{t-27} + \beta_2*RC3_{t-3} + \beta_3*RC7_{t-7} + \epsilon_t
          \]
#+END_EXPORT 
** Os Modelos de Deep Learning Bayesianos
- Consideram a incerteza do modelo e a propagam até a predição.
- Geram uma distribuição de probabilidade para cada predição.
- Escalam facilmente para dezenas ou centenas de milhares de entradas de dados.
- Podem facilmente agregar séries exógenas na predição.
- Não dependem de estacionariedade dos dados. 
    **i.e. podem gerar predições em regimes de anomalia**
** Rede Encoder Decoder (Treino)
   

#+BEGIN_EXPORT latex
\begin{figure}[H]
  \centering
  \includegraphics[width=0.9\columnwidth]{figuras/uber-train.png}
  \caption{Modelo durante o Treinamento }

\label{img:uber1}
\end{figure}
#+END_EXPORT

** Rede Encoder Decoder (Inferência)
   

#+BEGIN_EXPORT latex
\begin{figure}[H]
  \centering
  \includegraphics[width=0.9\columnwidth]{figuras/uber-predict.png}
  \caption{No módulo de inferência usamos uma rede neural simples para gerar
    predições a partir da codificação aprendida durante o pré-treino }
  \label{img:uber2}
\end{figure}

#+END_EXPORT
** Deep AR (Treino)
- Modelo Auto-regressivo 
#+BEGIN_EXPORT latex
\begin{figure}[H]
  \centering
  \includegraphics[width=0.9\columnwidth]{figuras/deepar-train.pdf}
  \caption{Para o treino, o modelo é guiado por anotações reais de valores
    passados da série alvo $y$ e as variáveis independentes $x$. Usamos o estado
  $h$ da rede LSTM a cada iteração temporal para calcular $\mu$  e $\sigma$.
  Esses valores são então usados no calculo da verossimilhança $p(y |
  \mu,\sigma)$, o valor que é minimizado.}
  \label{fig:deepartrain}
\end{figure}
#+END_EXPORT

** Deep AR (Inferência)
- Modelo Auto-regressivo 
#+BEGIN_EXPORT latex
\begin{figure}[H]
  \centering
  \includegraphics[width=0.9\columnwidth]{figuras/deepar-pred.pdf}
  \caption{Se desejarmos prever mais de um valor da série-alvo $y$ no futuro. O
    modelo é realimentado com os valores amostrados de $y^*$ e a rede continua a
  realizar predições.}
  \label{fig:deepartrain}
\end{figure}

#+END_EXPORT
** Deep Factors
   - Gera predições de maneira similar ao Encoder-Decoder.
   - Gera incerteza por meio de um Processo Gaussiano.
   - O Processo Gaussiano supõe que as predições são normalmente distribuídas 2 a 2.
   - O Kernel escolhido como função de covariância do processo 
   é usado para maximizar a verossimilhança das predições.
** Treinamento 
#+BEGIN_EXPORT latex
\animategraphics[loop,controls,width=\linewidth]{50}{figuras/gifs/dl-}{0}{9}
#+END_EXPORT 
* Resultados
** Métricas 
- $R^2$ 
Reporta a proporcão da variância da variável dependente que foi explicada pelo modelo.
#+BEGIN_EXPORT latex
\begin{align}
&R^2 = 1 - \frac{SS_{res}}{SS_{tot}} &\\
&SS_{tot} = \sum^n_{i=1} (y_i- \bar{y_i})^2 &\\
&SS_{res} = \sum^n_{i=1} (y_i - \hat{y})^2 &\\
&\bar{y} = \frac{1}{n} \sum^n_{i=1} y &
\end{align}
#+END_EXPORT 
   
** Métricas (2)
- RMSE
Raiz do erro quadrático médio para obtermos um erro na mesma ordem de grandeza da variável alvo.

#+BEGIN_EXPORT latex
\[
RMSE = \sqrt{\sum^n_{i=1}\frac{(\hat{y_i} - y_i)^2}{n}}
\]
#+END_EXPORT 

** Resultados (Tabela) 
#+BEGIN_EXPORT latex

\begin{center}
  \begin{table}[htbp]
    \caption{Comparação dos modelos de Deep Learning e o modelo Linear}
    \centering
  \begin{tabular}{l|llll}
    \cline{2-4}
    & \multicolumn{1}{l|}{RMSE 24h} & \multicolumn{1}{l|}{RMSE 48h} & \multicolumn{1}{l|}{RMSE 72h} &  \\ \cline{1-4}
    \multicolumn{1}{|l|}{DeepAR}               &               0.07                &          1.37                     &           1.44                    &  \\ \cline{1-1}
    \multicolumn{1}{|l|}{Enc-Dec-Forecaster}   &                   0.06            &        0.44                       &       0.80                        &  \\ \cline{1-1}
    \multicolumn{1}{|l|}{Deep Factors}         &              0.18                 &           2.36                    &                   1.83            &  \\ \cline{1-1}
    \multicolumn{1}{|l|}{Linear Coupled Model} &                  1.79             &       1.47                        &     2.36                          &  \\ \cline{1-1}
    \multicolumn{1}{|l|}{AR Process} &                  0.33             &       4.32                        &     5.48                          &  \\ \cline{1-1}
  \end{tabular}
  \end{table}
\end{center}

#+END_EXPORT 

** Resultados (Distribuição)
#+BEGIN_EXPORT latex

\begin{figure}[H]
\centering
\includegraphics[width=.3\textwidth]{figuras/qq_deep_ar.pdf} \hfill
\includegraphics[width=.3\textwidth]{figuras/qq_deep_factors.pdf} \hfill
\includegraphics[width=.3\textwidth]{figuras/qq_enc_dec.pdf} 
\caption{Valores reais plotados contra os valores previstos para análise da distribuição aprendida por cada modelo} 
\label{fig:distr}
\end{figure}

#+END_EXPORT 
** Resultados Deep AR 
[[file:figuras/forecast_deep_ar.pdf]]
** Resultados Encoder Decoder Forecaster 
[[file:figuras/forecast_enc_dec.pdf]]
** Resultados Deep Factors
[[file:figuras/forecast_deep_factors.pdf]]
** Resultados Processo AR
  - Realizado em período estacionário dos dados de treino 
  [[file:figuras/arppreds.pdf]]

** Resultados Coupled Linear Model
  [[file:figuras/predgrecialin.pdf]]
** Bibliografia
 :PROPERTIES:
 :BEAMER_opt: allowframebreaks,label=
 :END:

#+BEGIN_EXPORT latex
\printbibliography
#+END_EXPORT 
